function y = notchfilter(x)
%NOTCHFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 31-Aug-2017 10:31:04

persistent Hd;

if isempty(Hd)
    
    N  = 6;     % Order
    F0 = 0.15;  % Center frequency
    Q  = 2.5;   % Q-factor
    
    h = fdesign.notch('N,F0,Q', N, F0, Q);
    
    Hd = design(h, 'butter', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


